### ISSUE TITLE
Creating a deteministic Prisma/Vercel build fix.

### ISSUE THREAD

**Issue by Manoj-Axelsson** [Manoj-Axelsson/JobSeekeR-OSS#13]

**Comment by Manoj-Axelsson** [comment]
## Problem

Vercel Preview deployment fails during the TypeScript stage after PR #10.

The failure is:

`Property 'searchProfile' does not exist on type 'PrismaClient...'`

The repository Prisma schema contains the `SearchProfile` model, and running:

`npx prisma generate`

locally regenerates Prisma Client successfully.

After regeneration, the local production build completes successfully:

`npm run build`

## Evidence

- V2 PR #10 merged successfully into `Develop`.
- Vercel Preview build fails during TypeScript validation.
- Local `prisma generate` + production build succeeds.
- The failure indicates that the deployment build is using a Prisma Client that does not reflect the current schema.

## Objective

Make Prisma Client generation deterministic during the Vercel build lifecycle.

## Scope

- Add the minimal repository-level configuration required to ensure Prisma Client is generated before the Next.js production build.
- Do not modify V2 matcher logic.
- Do not modify the Prisma schema.
- Do not introduce architectural changes.
- Preserve the existing npm/Next.js build configuration.

## Validation

- `npx prisma generate`
- `npm run build`
- `npm run lint`
- Vercel Preview deployment succeeds.

## Acceptance Criteria

- A fresh Vercel deployment generates Prisma Client from the current schema.
- `SearchProfile` is available to the generated Prisma Client during the build.
- Production build completes successfully.
- No V2 application logic is changed.
